### ISSUE TITLE
`@Mock` doesn't work when using nima test

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-nima#14]
Got an actual problem this time, when using `@Mock` and injecting an Http Client the client is injected into the test class but the 
 mocked bean does not replace the one in the scope.

**Comment by SentryMan** [comment]
hmm, would this be an inject bug or an avaje nima bug?

**Comment by SentryMan** [comment]
once again, the error is mine, it seems I get it working if I don't add static when injecting the client

**Comment by rob-bygrave** [comment]
> it seems I get it working if I don't add static when injecting the client

This does not make sense to me in that both static and non-static/instance are valid scopes.

Did this test use `@Mock` or `@Inject`?  It could be that I'm assuming HttpClient is used with `@Inject` and maybe that is confusing ?

**Comment by SentryMan** [comment]
> Did this test use @Mock or @Inject? It could be that I'm assuming HttpClient is used with @Inject and maybe that is confusing ?

looked like this:
```
@InjectTest
TestyMcTest {
 @Inject static HttpClient client;
 @Mock Service mocky; //<- doesn't get added to beanscope
}
```

**Comment by rob-bygrave** [comment]
> @Mock Service mocky; //<- doesn't get added to beanscope

Right, so the HttpClient is **_static_** scope ... and that means that the http server that it will hit/access is also "wired" to the static scope.

So the `@Mock Service mocky` will be injected as a mock into the **_instance_** scope ... but **_IF_** the test is using the httpClient, that httpClient will hit the static scoped server instance which will NOT include that mock.

If it was the other way around like:

```java
 @Inject HttpClient client;
 static @Mock Service mocky;
```

Or the same scope ... then tests can use both.


> doesn't get added to beanscope

This statement is _NOT_ correct. It is getting added to a beanScope ... it's that there are MULTIPLE BeanScopes (the static one and the instance one).  The static scoped HttpClient will hit the static scoped Helidon instance (and that instance is created once at static class beforeAll time ...
