### ISSUE TITLE
What if we made this an Inject Plugin?

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-nima#2]
And provide a default Nima instance via the enhanced PostContruct. Something like this:

```
public final class DefaultNimaProvider implements io.avaje.inject.spi.Plugin {

  @Override
  public Class<?>[] provides() {
    return new Class<?>[] {WebServer.class};
  }

  @Override
  public void apply(BeanScopeBuilder builder) {

    final var nima = Nima.builder();
    builder.addPostConstruct(nima::configure);
    builder.propertyPlugin().get("server.port").map(Integer::valueOf).ifPresent(nima::port);
    builder.provideDefault(null, WebServer.class, nima::build);
  }
}

```

**Comment by rbygrave** [comment]
I'm not sure about Nima as a plugin.

In terms of the bootstrap / `public static void main()` method ... there is the need to:
- load external configuration (e.g. from secret store)
- initialise logging (logbook or maybe juli even)
- start the application (DI wiring + start http server + take into account shutdown hooks (we typically desire a single shutdown hook with control of the shutdown execution order)

I think I need to look at the logging setup that Helidon is proposing to use and see how that fits into the bootstrapping.

My gut says that Nima is this code that is in that main method and not really a plugin.

**Comment by SentryMan** [comment]
yeah I'm not really feeling it anymore either
